package com.codename1.css.tests.roundrect;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import static com.codename1.ui.ComponentSelector.$;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.Border;
import com.codename1.ui.plaf.RoundRectBorder;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class RoundRectDemo {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        try {
            Resources css = Resources.openLayered("/theme.css");
            UIManager.getInstance().addThemeProps(css.getTheme(css.getThemeResourceNames()[0]));
        } catch (Throwable t) {
            Log.e(t);
        }

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World", "RoundRectLabel"));
        hi.add(new Label("Round on top", "RoundRectLabelTopOnly"));
        hi.add(new Label("Round on bottom", "RoundRectLabelBottomOnly"));
        hi.add(new Label("Stroked", "RoundRectLabelStroked"));
        hi.add(new Label("With Shadow", "RoundRectLabelWithShadow"));
        hi.add(new Label("With Shadow Blur", "RoundRectLabelWithShadowBlur"));
        $("RoundRectLabelTopOnly", hi).each(c->{
            Border b = c.getStyle().getBorder();
            if (b instanceof RoundRectBorder) {
                System.out.println(((RoundRectBorder)b).isTopOnlyMode());
            }
        });
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
