/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.plaf.UIManager;
            import com.codename1.ui.list.DefaultListModel;import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class ArticleListFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
private UIManager ui;
public ArticleListFormTpl(java.util.Map context){
ui = (UIManager)context.get("ui");
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BoxLayout rootLayout = new BoxLayout(BoxLayout.Y_AXIS);
root.setLayout(rootLayout);
root.setUIID("NoPadding");
root.setName("articleList");
_nameIndex.put("articleList", root);
Container node1 = new Container();
LayeredLayout node1Layout = new LayeredLayout();
node1.setLayout(node1Layout);
node1.setUIID("NoPadding");
node1.setName("featuredArticle");
_nameIndex.put("featuredArticle", node1);
Container node2 = new Container();
BoxLayout node2Layout = new BoxLayout(BoxLayout.Y_AXIS);
node2.setLayout(node2Layout);
node2.setUIID("NoPadding");
Label node3 = new Label();
node3.setUIID("NoPaddingLabel");
node3.setIcon(resources.getImage("RedPlanet.png"));
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node3.getParent()){
node2.addComponent(node3);
}
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node2.getParent()){
node1.addComponent(node2);
}
Container node4 = new Container();
BorderLayout node4Layout = new BorderLayout();
node4.setLayout(node4Layout);
node4.setUIID("NoPadding");
Container node5 = new Container();
BoxLayout node5Layout = new BoxLayout(BoxLayout.Y_AXIS);
node5.setLayout(node5Layout);
node5.setUIID("NoPadding");
SpanLabel node6 = new SpanLabel();
node6.setUIID("ArticleHeadline");
node6.setText("Astronauts could land on Red Planet by 2039");
init1_node6(node6, node5);
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node5 != node6.getParent()){
node5.addComponent(node6);
}
Container node7 = new Container();
BorderLayout node7Layout = new BorderLayout();
node7.setLayout(node7Layout);
node7.setUIID("ArticleCommandArea");
Container node8 = new Container();
FlowLayout node8Layout = new FlowLayout();
node8.setLayout(node8Layout);
Button node9 = new Button();
node9.setUIID("NUISourceButton50White");
node9.setName("sourceButton");
_nameIndex.put("sourceButton", node9);
node9.setText("SPACE.com");
if (node9.getClientProperty("__CN1ML_NO_ADD__") == null && node8 != node9.getParent()){
node8.addComponent(node9);
}
Button node10 = new Button();
node10.setUIID("NUIDateButton50White");
node10.setName("dateButton");
_nameIndex.put("dateButton", node10);
node10.setText("20m ago");
if (node10.getClientProperty("__CN1ML_NO_ADD__") == null && node8 != node10.getParent()){
node8.addComponent(node10);
}
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && node7 != node8.getParent()){
node7.addComponent(BorderLayout.WEST, node8);
}
Container node11 = new Container();
FlowLayout node11Layout = new FlowLayout();
node11.setLayout(node11Layout);
Button node12 = new Button();
node12.setUIID("NUICategoryButtonLight");
node12.setName("categoryButton");
_nameIndex.put("categoryButton", node12);
node12.setText("SCIENCE");
if (node12.getClientProperty("__CN1ML_NO_ADD__") == null && node11 != node12.getParent()){
node11.addComponent(node12);
}
if (node11.getClientProperty("__CN1ML_NO_ADD__") == null && node7 != node11.getParent()){
node7.addComponent(BorderLayout.EAST, node11);
}
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node5 != node7.getParent()){
node5.addComponent(node7);
}
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node4 != node5.getParent()){
node4.addComponent(BorderLayout.SOUTH, node5);
}
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node4.getParent()){
node1.addComponent(node4);
}
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(node1);
}
init2_root(root, null);
return root;
}
public Container getArticleList(){
      return (Container)get("articleList");
      }
public Container getFeaturedArticle(){
      return (Container)get("featuredArticle");
      }
private void init1_node6(SpanLabel self, Container parent){
self.setTextUIID("ArticleHeadlineText");

}
public Button getSourceButton(){
      return (Button)get("sourceButton");
      }
public Button getDateButton(){
      return (Button)get("dateButton");
      }
public Button getCategoryButton(){
      return (Button)get("categoryButton");
      }
private void init2_root(Container self, Container parent){
self.setScrollableY(true);

}
}