/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class ChannelFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public ChannelFormTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BoxLayout rootLayout = new BoxLayout(BoxLayout.Y_AXIS);
root.setLayout(rootLayout);
Container node1 = new Container();
BoxLayout node1Layout = new BoxLayout(BoxLayout.Y_AXIS);
node1.setLayout(node1Layout);
node1.setUIID("NUIFormHeadingArea");
Label node2 = new Label();
node2.setUIID("NUIHeadingLabel");
node2.setText("SCIENCE CHANNEL");
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node2.getParent()){
node1.addComponent(node2);
}
Button node3 = new Button();
node3.setUIID("NUIPillButtonWhite");
node3.setText("Following");
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node3.getParent()){
node1.addComponent(node3);
}
Label node4 = new Label();
node4.setUIID("NUISubheadingLabelWhite");
node4.setText("234K Followers");
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node4.getParent()){
node1.addComponent(node4);
}
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(node1);
}
Container node5 = new Container();
FlowLayout node5Layout = new FlowLayout();
node5.setLayout(node5Layout);
Container node6 = new Container();
TableLayout node6Layout = new TableLayout(2,2);
node6.setLayout(node6Layout);
Container node7 = new Container();
FlowLayout node7Layout = new FlowLayout();
node7.setLayout(node7Layout);
init1_node7(node7, node6);
node7.addComponent(new Label("Name"));
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node7.getParent()){
node6.addComponent(node7);
}
Container node8 = new Container();
FlowLayout node8Layout = new FlowLayout();
node8.setLayout(node8Layout);
init2_node8(node8, node6);
TextField node9 = new TextField();
node9.setName("nameField");
_nameIndex.put("nameField", node9);
if (node9.getClientProperty("__CN1ML_NO_ADD__") == null && node8 != node9.getParent()){
node8.addComponent(node9);
}
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node8.getParent()){
node6.addComponent(node8);
}
Container node10 = new Container();
FlowLayout node10Layout = new FlowLayout();
node10.setLayout(node10Layout);
init3_node10(node10, node6);
Button node11 = new Button();
node11.setName("submit");
_nameIndex.put("submit", node11);
node11.setText("Submit");
if (node11.getClientProperty("__CN1ML_NO_ADD__") == null && node10 != node11.getParent()){
node10.addComponent(node11);
}
if (node10.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node10.getParent()){
node6.addComponent(node10);
}
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node5 != node6.getParent()){
node5.addComponent(node6);
}
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && root != node5.getParent()){
root.addComponent(BorderLayout.CENTER, node5);
}
Container node12 = new Container();
FlowLayout node12Layout = new FlowLayout();
node12.setLayout(node12Layout);
node12.addComponent(new Label("Good Bye World"));
if (node12.getClientProperty("__CN1ML_NO_ADD__") == null && root != node12.getParent()){
root.addComponent(BorderLayout.SOUTH, node12);
}
init4_root(root, null);
return root;
}
private void init1_node7(Container self, Container parent){
TableLayout l = (TableLayout)parent.getLayout(); TableLayout.Constraint c = l.createConstraint(0,0); c.setVerticalSpan(1); c.setHorizontalSpan(1); parent.addComponent(c, self);
}
private void init2_node8(Container self, Container parent){
TableLayout l = (TableLayout)parent.getLayout(); TableLayout.Constraint c = l.createConstraint(0,1); c.setVerticalSpan(1); c.setHorizontalSpan(1); parent.addComponent(c, self);
}
public TextField getNameField(){
      return (TextField)get("nameField");
      }
private void init3_node10(Container self, Container parent){
TableLayout l = (TableLayout)parent.getLayout(); TableLayout.Constraint c = l.createConstraint(1,0); c.setVerticalSpan(1); c.setHorizontalSpan(2); parent.addComponent(c, self);
}
public Button getSubmit(){
      return (Button)get("submit");
      }
private void init4_root(Container self, Container parent){
self.setScrollableY(true);

}
}