/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class CoolButtonsFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public CoolButtonsFormTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BoxLayout rootLayout = new BoxLayout(BoxLayout.Y_AXIS);
root.setLayout(rootLayout);
root.setUIID("GradientContainer");
Label node1 = new Label();
node1.setText("Round1 Empty In Grid");
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(node1);
}
Container node2 = new Container();
GridLayout node2Layout = new GridLayout(2,3);
node2.setLayout(node2Layout);
Button node3 = new Button();
node3.setUIID("Round1");
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node3.getParent()){
node2.addComponent(node3);
}
Button node4 = new Button();
node4.setUIID("Round1");
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node4.getParent()){
node2.addComponent(node4);
}
Button node5 = new Button();
node5.setUIID("Round1Gradient");
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node5.getParent()){
node2.addComponent(node5);
}
Button node6 = new Button();
node6.setUIID("Round1InnerShadow");
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node6.getParent()){
node2.addComponent(node6);
}
Button node7 = new Button();
node7.setUIID("Round1InnerShadow");
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node7.getParent()){
node2.addComponent(node7);
}
Button node8 = new Button();
node8.setUIID("Round1OuterShadow");
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node8.getParent()){
node2.addComponent(node8);
}
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && root != node2.getParent()){
root.addComponent(node2);
}
Label node9 = new Label();
node9.setText("Round1 In BoxLayout Y");
if (node9.getClientProperty("__CN1ML_NO_ADD__") == null && root != node9.getParent()){
root.addComponent(node9);
}
Button node10 = new Button();
node10.setUIID("Round1");
if (node10.getClientProperty("__CN1ML_NO_ADD__") == null && root != node10.getParent()){
root.addComponent(node10);
}
Button node11 = new Button();
node11.setUIID("Round1");
node11.setText("With Label");
if (node11.getClientProperty("__CN1ML_NO_ADD__") == null && root != node11.getParent()){
root.addComponent(node11);
}
Button node12 = new Button();
node12.setUIID("Round1InnerShadow");
node12.setText("With Inner Shadow");
if (node12.getClientProperty("__CN1ML_NO_ADD__") == null && root != node12.getParent()){
root.addComponent(node12);
}
Button node13 = new Button();
node13.setUIID("Round1OuterShadow");
node13.setText("With Outer Shadow");
if (node13.getClientProperty("__CN1ML_NO_ADD__") == null && root != node13.getParent()){
root.addComponent(node13);
}
Button node14 = new Button();
node14.setUIID("Round1Gradient");
node14.setText("With Shadow & Gradient");
if (node14.getClientProperty("__CN1ML_NO_ADD__") == null && root != node14.getParent()){
root.addComponent(node14);
}
return root;
}
}