/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class LoginFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public LoginFormTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BorderLayout rootLayout = new BorderLayout();
root.setLayout(rootLayout);
root.setUIID("NUILoginForm");
Container node1 = new Container();
FlowLayout node1Layout = new FlowLayout(Component.CENTER);
node1.setLayout(node1Layout);
init1_node1(node1, root);
node1.addComponent(new Label(resources.getImage("NowLogo.png")));
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(BorderLayout.CENTER, node1);
}
Container node2 = new Container();
BoxLayout node2Layout = new BoxLayout(BoxLayout.Y_AXIS);
node2.setLayout(node2Layout);
TextField node3 = new TextField();
node3.setName("usernameField");
_nameIndex.put("usernameField", node3);
init2_node3(node3, node2);
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node3.getParent()){
node2.addComponent(node3);
}
TextField node4 = new TextField();
node4.setConstraint(TextArea.PASSWORD);
node4.setName("passwordField");
_nameIndex.put("passwordField", node4);
init3_node4(node4, node2);
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node4.getParent()){
node2.addComponent(node4);
}
Button node5 = new Button();
node5.setName("submitButton");
_nameIndex.put("submitButton", node5);
node5.setText("Get Started");
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node5.getParent()){
node2.addComponent(node5);
}
Container node6 = new Container();
BorderLayout node6Layout = new BorderLayout();
node6.setLayout(node6Layout);
Button node7 = new Button();
node7.setUIID("NUILinkButtonLight");
node7.setName("signupButton");
_nameIndex.put("signupButton", node7);
node7.setText("Create Account");
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node7.getParent()){
node6.addComponent(BorderLayout.WEST, node7);
}
Button node8 = new Button();
node8.setUIID("NUILinkButtonLight");
node8.setName("helpButton");
_nameIndex.put("helpButton", node8);
node8.setText("Need Help?");
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node8.getParent()){
node6.addComponent(BorderLayout.EAST, node8);
}
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node6.getParent()){
node2.addComponent(node6);
}
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && root != node2.getParent()){
root.addComponent(BorderLayout.SOUTH, node2);
}
return root;
}
private void init1_node1(Container self, Container parent){
((FlowLayout)self.getLayout()).setValign(Component.CENTER);
}
public TextField getUsernameField(){
      return (TextField)get("usernameField");
      }
private void init2_node3(TextField self, Container parent){
self.setHint("Username");

}
public TextField getPasswordField(){
      return (TextField)get("passwordField");
      }
private void init3_node4(TextField self, Container parent){
self.setHint("Password");

}
public Button getSubmitButton(){
      return (Button)get("submitButton");
      }
public Button getSignupButton(){
      return (Button)get("signupButton");
      }
public Button getHelpButton(){
      return (Button)get("helpButton");
      }
}