/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class NUIArticleListItemTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public NUIArticleListItemTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BoxLayout rootLayout = new BoxLayout(BoxLayout.Y_AXIS);
root.setLayout(rootLayout);
root.setUIID("ArticleListItem");
SpanLabel node1 = new SpanLabel();
node1.setUIID("NUIArticleListItemHeadline");
node1.setName("headlineLabel");
_nameIndex.put("headlineLabel", node1);
node1.setText("Arctic sea ice extent hits record low for winter maximum");
init1_node1(node1, root);
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(node1);
}
Container node2 = new Container();
BorderLayout node2Layout = new BorderLayout();
node2.setLayout(node2Layout);
node2.setUIID("ArticleCommandArea");
Container node3 = new Container();
FlowLayout node3Layout = new FlowLayout();
node3.setLayout(node3Layout);
Button node4 = new Button();
node4.setUIID("NUISourceButton30");
node4.setName("sourceButton");
_nameIndex.put("sourceButton", node4);
node4.setText("CNN");
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node3 != node4.getParent()){
node3.addComponent(node4);
}
Button node5 = new Button();
node5.setUIID("NUIDateButton30");
node5.setName("dateButton");
_nameIndex.put("dateButton", node5);
node5.setText("1h ago");
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node3 != node5.getParent()){
node3.addComponent(node5);
}
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node3.getParent()){
node2.addComponent(BorderLayout.WEST, node3);
}
Container node6 = new Container();
FlowLayout node6Layout = new FlowLayout();
node6.setLayout(node6Layout);
Button node7 = new Button();
node7.setUIID("NUICategoryButton");
node7.setName("categoryButton");
_nameIndex.put("categoryButton", node7);
node7.setText("ENVIRONMENT");
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node6 != node7.getParent()){
node6.addComponent(node7);
}
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node2 != node6.getParent()){
node2.addComponent(BorderLayout.EAST, node6);
}
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && root != node2.getParent()){
root.addComponent(node2);
}
return root;
}
public SpanLabel getHeadlineLabel(){
      return (SpanLabel)get("headlineLabel");
      }
private void init1_node1(SpanLabel self, Container parent){
self.setTextUIID("NUIArticleListItemHeadlineText");

}
public Button getSourceButton(){
      return (Button)get("sourceButton");
      }
public Button getDateButton(){
      return (Button)get("dateButton");
      }
public Button getCategoryButton(){
      return (Button)get("categoryButton");
      }
}