/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class OverviewFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public OverviewFormTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BoxLayout rootLayout = new BoxLayout(BoxLayout.Y_AXIS);
root.setLayout(rootLayout);
Label node1 = new Label();
node1.setUIID("NUIHeadingLabel");
node1.setText("OVERVIEW");
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(node1);
}
Label node2 = new Label();
node2.setUIID("NUISubHeadingLabel");
node2.setText("What you are reading the most");
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && root != node2.getParent()){
root.addComponent(node2);
}
NUIProgress node3 = new NUIProgress();
init1_node3(node3, root);
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && root != node3.getParent()){
root.addComponent(node3);
}
NUIProgress node4 = new NUIProgress();
init2_node4(node4, root);
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && root != node4.getParent()){
root.addComponent(node4);
}
NUIProgress node5 = new NUIProgress();
init3_node5(node5, root);
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && root != node5.getParent()){
root.addComponent(node5);
}
NUIProgress node6 = new NUIProgress();
init4_node6(node6, root);
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && root != node6.getParent()){
root.addComponent(node6);
}
NUIProgress node7 = new NUIProgress();
init5_node7(node7, root);
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && root != node7.getParent()){
root.addComponent(node7);
}
NUIProgress node8 = new NUIProgress();
init6_node8(node8, root);
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && root != node8.getParent()){
root.addComponent(node8);
}
NUIProgress node9 = new NUIProgress();
init7_node9(node9, root);
if (node9.getClientProperty("__CN1ML_NO_ADD__") == null && root != node9.getParent()){
root.addComponent(node9);
}
init8_root(root, null);
return root;
}
private void init1_node3(NUIProgress self, Container parent){
self.setCategory("FASHION");
self.setProgress(34);

}
private void init2_node4(NUIProgress self, Container parent){
self.setCategory("ENVIRONMENT");
self.setProgress(28);

}
private void init3_node5(NUIProgress self, Container parent){
self.setCategory("TECHNOLOGY");
self.setProgress(12);

}
private void init4_node6(NUIProgress self, Container parent){
self.setCategory("AUTO");
self.setProgress(10);

}
private void init5_node7(NUIProgress self, Container parent){
self.setCategory("FINANCES");
self.setProgress(8);

}
private void init6_node8(NUIProgress self, Container parent){
self.setCategory("SCIENCE");
self.setProgress(5);

}
private void init7_node9(NUIProgress self, Container parent){
self.setCategory("SPORT");
self.setProgress(3);

}
private void init8_root(Container self, Container parent){
self.setScrollableY(true);

}
}