/* THIS FILE IS AUTOMATICALLY GENERATED-- DO NOT MODIFY IT*/
package com.codename1.themes.nowui;
import com.codename1.ui.*;
import com.codename1.components.*;
import com.codename1.ui.layouts.*;
import com.codename1.ui.table.*;
import com.codename1.ui.util.*;
class SignupFormTpl {
private Container rootContainer;
private Resources resources;
public Container getRoot(){ if (rootContainer==null){ 
        try {rootContainer=buildUI();} catch (Exception ex){ex.printStackTrace();throw new RuntimeException(ex.getMessage());}} return rootContainer;}
private java.util.Map<String,Component> _nameIndex=new java.util.HashMap<String,Component>();
public Component get(String name){ getRoot(); return _nameIndex.get(name);}
public SignupFormTpl(java.util.Map context){
for (Object o : context.values()){ if (o instanceof Resources) resources=(Resources)o;}
}
private Container buildUI() throws Exception {
Container root = new Container();
BorderLayout rootLayout = new BorderLayout();
root.setLayout(rootLayout);
Container node1 = new Container();
BoxLayout node1Layout = new BoxLayout(BoxLayout.Y_AXIS);
node1.setLayout(node1Layout);
Label node2 = new Label();
node2.setUIID("h1");
node2.setText("CREATE ACCOUNT");
if (node2.getClientProperty("__CN1ML_NO_ADD__") == null && node1 != node2.getParent()){
node1.addComponent(node2);
}
if (node1.getClientProperty("__CN1ML_NO_ADD__") == null && root != node1.getParent()){
root.addComponent(BorderLayout.NORTH, node1);
}
Container node3 = new Container();
BorderLayout node3Layout = new BorderLayout();
node3.setLayout(node3Layout);
Container node4 = new Container();
BoxLayout node4Layout = new BoxLayout(BoxLayout.Y_AXIS);
node4.setLayout(node4Layout);
TextField node5 = new TextField();
node5.setName("nameField");
_nameIndex.put("nameField", node5);
init1_node5(node5, node4);
if (node5.getClientProperty("__CN1ML_NO_ADD__") == null && node4 != node5.getParent()){
node4.addComponent(node5);
}
TextField node6 = new TextField();
node6.setName("emailField");
_nameIndex.put("emailField", node6);
init2_node6(node6, node4);
if (node6.getClientProperty("__CN1ML_NO_ADD__") == null && node4 != node6.getParent()){
node4.addComponent(node6);
}
TextField node7 = new TextField();
node7.setName("passwordField");
_nameIndex.put("passwordField", node7);
init3_node7(node7, node4);
if (node7.getClientProperty("__CN1ML_NO_ADD__") == null && node4 != node7.getParent()){
node4.addComponent(node7);
}
if (node4.getClientProperty("__CN1ML_NO_ADD__") == null && node3 != node4.getParent()){
node3.addComponent(BorderLayout.SOUTH, node4);
}
if (node3.getClientProperty("__CN1ML_NO_ADD__") == null && root != node3.getParent()){
root.addComponent(BorderLayout.CENTER, node3);
}
Container node8 = new Container();
BoxLayout node8Layout = new BoxLayout(BoxLayout.Y_AXIS);
node8.setLayout(node8Layout);
Button node9 = new Button();
node9.setUIID("ClearButton");
node9.setName("continueButton");
_nameIndex.put("continueButton", node9);
node9.setText("Continue");
if (node9.getClientProperty("__CN1ML_NO_ADD__") == null && node8 != node9.getParent()){
node8.addComponent(node9);
}
Button node10 = new Button();
node10.setUIID("NUILinkButtonLight");
node10.setName("termsButton");
_nameIndex.put("termsButton", node10);
node10.setText("Terms & Conditions");
if (node10.getClientProperty("__CN1ML_NO_ADD__") == null && node8 != node10.getParent()){
node8.addComponent(node10);
}
if (node8.getClientProperty("__CN1ML_NO_ADD__") == null && root != node8.getParent()){
root.addComponent(BorderLayout.SOUTH, node8);
}
return root;
}
public TextField getNameField(){
      return (TextField)get("nameField");
      }
private void init1_node5(TextField self, Container parent){
self.setHint("Name");

}
public TextField getEmailField(){
      return (TextField)get("emailField");
      }
private void init2_node6(TextField self, Container parent){
self.setHint("Email");

}
public TextField getPasswordField(){
      return (TextField)get("passwordField");
      }
private void init3_node7(TextField self, Container parent){
self.setHint("Password");

}
public Button getContinueButton(){
      return (Button)get("continueButton");
      }
public Button getTermsButton(){
      return (Button)get("termsButton");
      }
}